name: Run e2e tests

on: [pull_request]

jobs:
  run_e2e:
    name: Run e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        go-version: [1.18.0, 1.19.4]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Run format check
        run: pnpm run format:check
      - name: Run linter
        run: pnpm run nx affected:lint
      - name: Run e2e test
        run: pnpm run nx affected:e2e
