name: Bump version and tagging

on:
  push:
    branches:
      - main

jobs:
  version_bump_and_tagging:
    name: Version bump and tagging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        go-version: [1.18.0]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Run auto version
        run: |
          git config --global user.email "di.zou1214@gmail.com"
          git config --global user.name "Di Zou"
          pnpm exec nx run gin:version --push
